apiVersion: batch/v1
kind: Job
metadata:
  name: solr-init
spec:
  template:
    spec:
      imagePullSecrets:
        - name: sitecore-docker-registry
      nodeSelector:
        kubernetes.io/os: windows        
        group: data
      containers:
      - name: solr-init
        image: 197804015172.dkr.ecr.us-east-1.amazonaws.com/sitecore-xp1-solr-init:latest
        env:
        - name: SITECORE_SOLR_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: sitecore-solr
              key: sitecore-solr-connection-string.txt
      restartPolicy: Never
  backoffLimit: 5
