version: 0.2
env:
  parameter-store:
    AWS_ACCESS_KEY_ID: access_key
    AWS_SECRET_ACCESS_KEY: secret_key
    AWS_REGION: region
  
phases:

  install:
    commands:
      - aws sts get-caller-identity
  pre_build:
    commands:
      - echo Logging in to Amazon EKS...
      - echo check config 
      - echo check kubectl access
      - powershell.exe
      - aws.exe configure get list
      - kubectl get svc
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 636494690103.dkr.ecr.us-west-2.amazonaws.com
      

  build:
    commands:
      - echo Build started on `date`
      - echo Pulling the Docker image...          

  post_build:
    commands:
      - echo Build completed on `date`
      - powershell.exe .\Init.ps1
      - powershell.exe
      - kubectl apply -k ./k8s/secrets/
      - kubectl apply -f ./k8s/external.yaml
