apiVersion: v1
kind: Service
metadata:
  name: solr
spec:
  selector:
    app: solr
  ports:
  - protocol: TCP
    port: 8983
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solr
  labels:
    app: solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solr
  template:
    metadata:
      labels:
        app: solr
    spec:
      nodeSelector:
        kubernetes.io/os: windows
        group: data
      containers:
      - name: solr
        image: 197804015172.dkr.ecr.us-east-1.amazonaws.com/solr:latest
        ports:
        - containerPort: 8983
        env:
        - name: SOLR_MODE
          value: solrcloud
      imagePullSecrets:
      - name: sitecore-docker-registry
